### ISSUE TITLE
Setup development environment on ~okeanos

### ISSUE THREAD

**Issue by NicolasLiampotis** [grnet/access-ca-portal#16]
Setup development environment on ~okeanos with the following resources:
- 2 VMs 
- 4 CPUs (in total)
- 4GB RAM (in total)
- 2 public IPs
- 20GB hdd (in total)

**Comment by NicolasLiampotis** [comment]
Submitted application for new project. Waiting for ~okeanos admin to confirm

**Comment by stevelaskaridis** [comment]
Just made join request.
Pending @arossiko join request and approval of the two. After this, this issue could be closed.

**Comment by NicolasLiampotis** [comment]
Both @stevelaskaridis and @arossiko accepted as members.
