### ISSUE TITLE
Verify checked-in Gemfile.lock is up2date

### ISSUE THREAD

**Issue by NicolasLiampotis** [grnet/access-ca-portal#31]
Use`.gitignore` [template from GitHub](https://github.com/github/gitignore/blob/master/Rails.gitignore) and adjust accordingly.

**Comment by NicolasLiampotis** [comment]
While at it, compare "Access" .gitignore file against the one proposed by GitHub (see link in description)

**Comment by stevelaskaridis** [comment]
## .gitignore

Pretty much the same.

## Gemfile.lock

> the Gemfile.lock makes your application a single package of both your own code and the third-party code it ran the last time you know for sure that everything worked. [...]
> The next time you run bundle install on the same machine, bundler will see that it already has all of the dependencies you need, and skip the installation process.
> [http://bundler.io/v1.3/rationale.html](http://bundler.io/v1.3/rationale.html)

In other words, running bundle install will look at the Gemfile.lock and install the exact same versions, rather than just using the Gemfile and installing the most recent versions.
[stackoverflow.com](http://stackoverflow.com/questions/6927442/what-is-the-difference-between-gemfile-and-gemfile-lock-in-ruby-on-rails)

**Comment by NicolasLiampotis** [comment]
Checked in Gemfile.lock has indeed all required dependencies. However, when running `rake test` on my machine, Gemfile.lock gets updated:

```
diff --git a/access/Gemfile.lock b/access/Gemfile.lock
index fb75d81..537eb83 100644
--- a/access/Gemfile.lock
+++ b/access/Gemfile.lock
@@ -157,6 +157,3 @@ DEPENDENCIES
   turbolinks
   uglifier (>= 1.3.0)
   web-console (~> 2.0)
-
-BUNDLED WITH
-   1.10.6
```

That's probably because I'm using an older version of rake/bundler.

## Links
- [Do not update BUNDLED WITH if no other changes to the lock happened #3697](https://github.com/bundler/bundler/issues/3697)
- [How to stop rails from adding BUNDLED WITH to the Gemfile.lock](http://stackoverflow.com/questions/30713922/how-to-stop-rails-from-adding-bundled-with-to-the-gemfile-lock/30738987#30738987)
