### ISSUE TITLE
Application is not runnning as access user?

### ISSUE THREAD

**Issue by stevelaskaridis** [grnet/access-ca-portal#54]
## Description

The owner of the application - the user who runs the access web application under apache - is supposed to be defined by the `{{ application_user }}` ansible variable. Does it with the current config?

**Comment by arossiko** [comment]
The owner of the application is Passenger so if we want to change the user that runs the access web application we just have to change the Passenger user. In access.conf.j2 file there are these two lines:

```
    PassengerUserSwitching on
    PassengerUser {{application_user}}
```

for this purpose

**Comment by stevelaskaridis** [comment]
> By default, Phusion Passenger runs Rails applications as the owner of config.ru.

[Source](https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html)

**Comment by arossiko** [comment]
Yes but when we change the user of Phusion Passenger doesn't automatically change the user that runs the Rails application?

**Comment by NicolasLiampotis** [comment]
Just did a fresh Access installation on a CentOS 7 VM:

```
# ps -edaf |grep access
access   19671 19640  1 17:32 ?        00:00:03 Passenger AppPreloader: /var/www/access-ca-portal/access
access   19768 19671  0 17:32 ?        00:00:02 Passenger RubyApp: /var/www/access-ca-portal/access (development)
access   19776 19671  0 17:32 ?        00:00:00 Passenger RubyApp: /var/www/access-ca-portal/access (development)
```

In  `group_vars/web-servers`:

```
application_user: access
```

I'm confused - what's the issue with the current ansible playbook?

**Comment by stevelaskaridis** [comment]
## Passenger Application Owner

```
When user switching is enabled, the following rules are followed to determine what user an application should be run as. The first matching rule is the rule that will be followed.

1. If PassengerUser or PassengerGroup are set, then the application will be run as the specified user/group. Thus, these options are a good way to override user switching settings.
2. If the startup file is owned by root or an unknown user, then the application will run as the user specified by PassengerDefaultUser and PassengerDefaultGroup. This way, we discourage accidentally running applications as root, which is insecure.
3. Otherwise, the application is run as the owner of the startup file.
```

[Source](https://www.phusionpassenger.com/library/deploy/apache/user_sandboxing.html#red-hat-and-centos-caveats)

## Output of the process owner

```
[root@snf-684937 access]# ps -o pid,user,group,comm -p 26596
  PID USER     GROUP    COMMAND
26596 access   access   ruby
```

## Behaviour and actions

It seems like it **should** be running indeed with the current configuration as `{{ application_user }}`. However, that was not the case in my VM. I propose doing both ([1] and [3]) just to have a constant behaviour. I am introducing a new PR with the changes.

**Comment by stevelaskaridis** [comment]
## Update

Just set up a new VM and changed back the owner of **config.ru** to root and the application runs under `{{ application_user }}`.

I hope it was my fault and not to emerge again.

I am changing the label and context to question.
