### ISSUE TITLE
Segmentation fault when using therubyracer

### ISSUE THREAD

**Issue by stevelaskaridis** [grnet/access-ca-portal#55]
## Description

When using `therubyracer` and `libv8` as JSExec engine, the web application throws segmentation fault.
Even after changing the versions to **'0.12.2'** and  **'3.16.14.7'**, the problem persists. (see [here](https://github.com/cowboyd/therubyracer/issues/341) and [here](https://github.com/cowboyd/therubyracer/issues/317)).
## Proposed fix
- Change the execution engine to **nodejs** and after **therubyracer [v.1.0.0](https://github.com/cowboyd/therubyracer/milestones/v1.0.0)** we could change it back if fixed.
  - this is actually reverting commit b7046522507a735548a75088971f43a3ea054e1c

**Comment by NicolasLiampotis** [comment]
Let's go ahead with the proposed fix. 

_N.B._ It would be useful to include the error logs as well as the steps to reproduce the issue in the description.

**Comment by stevelaskaridis** [comment]
## Logs

http://pastebin.com/EzcXSAFY 

(_too long to embed in Github comment_)

**Comment by NicolasLiampotis** [comment]
Closing issue after moving back to using nodejs. If reverting to therubyracer as a JS runtime environment has advantages over nodejs then a new "enhancement" issue should be opened.

**Comment by NicolasLiampotis** [comment]
Perhaps therubyracer was not the way to go, regardless of the seg fault:
https://devcenter.heroku.com/articles/rails-asset-pipeline#therubyracer

**Comment by maesitos** [comment]
The therubyracer gave me the same problem also. Comment it on your Gemfile and install NodeJS in your system. Therubyracer is being used by [Execjs](https://github.com/sstephenson/execjs) and from the Readme:

> ExecJS lets you run JavaScript code from Ruby. **It automatically picks the best runtime available** to evaluate your JavaScript program, then returns the result to you as a Ruby object.
> 
> ExecJS supports these runtimes:
> 
> therubyracer - Google V8 embedded within Ruby
> therubyrhino - Mozilla Rhino embedded within JRuby
> Node.js
> Apple JavaScriptCore - Included with Mac OS X
> Microsoft Windows Script Host (JScript)

So just install another JS runtime enviroment
