### ISSUE TITLE
ExecJS::RuntimeError in People#index after installation

### ISSUE THREAD

**Issue by NicolasLiampotis** [grnet/access-ca-portal#72]
After installing "Access" on a fresh CentOS 7 VM using the latest ansible playbook from the devel branch, I get the following exception when accessing the webapp:

![screen shot 2015-11-14 at 02 26 03](https://cloud.githubusercontent.com/assets/1188170/11160784/7c48e40e-8a77-11e5-9187-08c8957fa84b.png)

**Comment by arossiko** [comment]
Yeah you must replace the sixth line of application.html.erb with the following:
<%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>

**Comment by stevelaskaridis** [comment]
@arossiko This change simply makes the website not to run any javascript.
Revert commit in #78.

**Comment by stevelaskaridis** [comment]
It's SELinux specific error. If you `setenforce 0`, make the request and then `setenforce 1`, it works.
Will have to find the specific policy missing and integrate it into the passenger.pp file, which in turn should be statically integrated to ansible.

**Comment by stevelaskaridis** [comment]
Solved with #79.
