### ISSUE TITLE
List of organisation names not localised

### ISSUE THREAD

**Issue by NicolasLiampotis** [grnet/access-ca-portal#8]
The list of organisation names is not localised during new user registration

#### How to reproduce:
1. Select English (https://access2.hellasgrid.gr/en)
2. Register Personal details (https://access2.hellasgrid.gr/en/register/registration_form):

![accesscaportal-userregistration-organisation](https://cloud.githubusercontent.com/assets/1188170/8778757/44b11a4a-2f08-11e5-870b-800537abfb43.png)

**Comment by stevelaskaridis** [comment]
Had not run the migrations introduced in the latest commit.
Closing issue.
