### ISSUE TITLE
Insert organization with all supported locales

### ISSUE THREAD

**Issue by stevelaskaridis** [grnet/access-ca-portal#82]
## Description

When inserting a new organization, the user-admin should be able to add a name for all the available locales the application is offering, without changing the current locale the website is served with.

**Comment by NicolasLiampotis** [comment]
Mostly addressed with PR #90.  
Still a couple of minor fixes required before closing:
- "New Organization" not translated when using `el` locale
- "Back" not translated when using `el` locale
