### ISSUE TITLE
Validation failed: Subject dn is not a valid DN when creating CSR from Chrome

### ISSUE THREAD

**Issue by NicolasLiampotis** [grnet/access-ca-portal#97]
#### Steps to reproduce:
1. Log into Access through Chrome browser
2. Select `Create new certificate request (browser)` 

![screen shot 2015-12-10 at 03 27 20](https://cloud.githubusercontent.com/assets/1188170/11704222/72caa148-9eee-11e5-927e-cc85958a93a0.png)

**Comment by stevelaskaridis** [comment]
I can create a CSR from Chromium (_Version 47.0.2498.0 (64-bit)_) without any problems. In fact, I just did.
Does your user have any other certificate requests?

Chromium supports the <keygen> tag, as I can deduce from [here](https://code.google.com/p/chromium/issues/detail?id=34607). However, there seems to be an intent to deprecate it. You can check [here](https://groups.google.com/a/chromium.org/forum/#!topic/net-dev/pX5NbX0Xack).

**Comment by NicolasLiampotis** [comment]
Fixed in PR #99
